repos:
- repo: https://github.com/pre-commit/mirrors-isort
  rev: master  # Use the revision sha / tag you want to point at
  hooks:
  - id: isort
    args: [-m3, --trailing-comma]

- repo: https://github.com/ambv/black
  rev: stable
  hooks:
    - id: black
      language_version: python3.7
      types: [file, python]

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.4.0
  hooks:
    - id: flake8
      language_version: python3.7
      args: [--max-line-length=100,--extend-ignore=E203]

- repo: local
  hooks:
    - id: flynt
      name: flynt
      entry: flynt
      args: [--fail-on-change]
      types: [file, python]
      language: python
      additional_dependencies:
          - flynt