version: 2.1

executors:
  python3-executor:
    docker:
      - image: circleci/python:3.7

jobs:

  syntax-check:
    executor: python3-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip3 install flake8

      - run:
          name: Run flake8
          command: |
            . venv/bin/activate
            flake8 --exclude venv --max-line-length=100 --extend-ignore=E203 --show-source

      - run:
          name: Check show-stoppers
          command: |
            . venv/bin/activate
            flake8 --exclude venv --count --select=E901,E999,F821,F822,F823 --show-source --statistics


workflows:
  version: 2
  syntax-quality:
    jobs:
      - syntax-check
